Feat/spring security 기능 구현 #51
FC-DEV-FinalProject/FinalProject_team3_BE pull request #105
Opened 2024-11-25 08:45 UTC by kendrickhama

## 📌 PR 개요
- spring security

## #️⃣연관된 이슈

> #51 

## 📝작업 내용
- JWT 생성 및 로그인
- access&refresh token
- 로그아웃 기능 구현

2024-11-25 09:46 UTC, ziguin0925 reviewed
리뷰 확인 부탁드립니다.

2024-11-25 09:47 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/controller/InvestorController.java
> +public class InvestorController {
해당 컨트롤러 사용안해서 빼도 괜찮을 것 같아요

2024-11-25 09:48 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/controller/ReIssueController.java
> +        String newAccess = jwtUtil.createJwt("access", username, role, 30 * 60 * 1000L); //30분
@Value ...

2024-11-25 09:52 UTC, ziguin0925 reviewed
리뷰 다시 올렸습니당

2024-11-26 05:54 UTC, ziguin0925 submitted a review, later dismissed
병훈님께도 pr 한번 말씀해주시고 진행해주세요. yaml파일 공유도...

2024-11-26 06:07 UTC, kbyunghoon requested changes
리뷰 확인해주세요

2024-11-26 06:07 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/security/handler/CustomAuthenticationSuccessHandler.java
> +        response.addCookie(createCookie("refresh", refresh));
리프레시 토큰을 Redis에 저장할 거면 해당 리프레시 토큰을 클라이언트에 넘길 필요 없습니다.

2024-11-26 06:07 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/util/JWTUtil.java
> +    public JWTUtil(@Value("${jwt.secret}") String secret) {
Value 따로 빼주세요

2024-11-26 06:07 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/util/RedisUtil.java
> +    }
여기도 확인해주세요

2024-11-27 12:49 UTC, kbyunghoon requested changes
리뷰 한번 확인해주세요

2024-11-27 12:49 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/config/SecurityConfig.java
> +            INVESTOR_ADMIN > INVESTOR
이 부분 수정안된건가요?? 아니면 이대로 가는게 맞는건가요?

2024-11-27 12:49 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/security/filter/CustomLogoutFilter.java
> +        response.setStatus(HttpServletResponse.SC_OK);
로그아웃은 컨트롤러로 따로 빼는 게 좋지 않을까요?

2024-11-28 05:02 UTC, kbyunghoon requested changes

2024-11-28 05:02 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/security/filter/JWTFilter.java
> +            jwtUtil.isExpired(accessToken);
isExpired 만료 안 될 경우 `false`지만
만료 될 경우에는 `true`를 반환하는 건 없어보입니다.
이 경우 isExpired에서 예외처리에서 return true로 하면 isExpired를 호출하는 코드에선 try catch를 더 이상 사용할 필요가 없지 않을까요?

2024-11-28 06:33 UTC, ziguin0925 reviewed
리뷰 남겼습니당

2024-11-28 06:33 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/dto/response/TokenResponse.java
> +public class TokenResponse {
해당 클래스도 사용하지 않는것 같은데 한번 확인 가능할까요?

2024-11-28 06:33 UTC, ziguin0925 commented on src/main/java/com/investmetic/global/config/SecurityConfig.java
> +                    config.setAllowedOrigins(List.of("http://localhost:3000"));
patch등 추가 부탁드릴게요

2024-11-28 10:44 UTC, kbyunghoon approved these changes

2024-11-28 10:46 UTC, merged