Feat/전략 승인 승인 거부 상태 변환 기능 #69
FC-DEV-FinalProject/FinalProject_team3_BE pull request #106
Opened 2024-11-25 10:05 UTC by ghkdwjdgk123

## 📌 PR 개요
- 이 PR의 목적과 변경된 내용을 간략히 설명하세요. 

## #️⃣연관된 이슈

> ex) #69
## 📝작업 내용

- 전략 승인 상태 변경 기능 구현 
- 전략 엔티티 전략 승인 상태 기본값 PENDING 으로 변경

2024-11-25 12:06 UTC, kbyunghoon requested changes
리뷰 남겼어요

2024-11-25 12:06 UTC, kbyunghoon commented on src/test/java/com/investmetic/domain/strategy/service/AdminStrategyServiceTest.java
> +    void UserDenyTest() {
카멜케이스 확인해주세요

2024-11-25 12:06 UTC, kbyunghoon commented on src/test/java/com/investmetic/domain/strategy/service/AdminStrategyServiceTest.java
> +        List<Strategy> DBstrategys = strategyRepository.findAll();
카멜케이스 확인해주세요

2024-11-25 12:06 UTC, kbyunghoon commented on src/test/java/com/investmetic/domain/strategy/service/AdminStrategyServiceTest.java
> +        List<Strategy> DBstrategys = strategyRepository.findAll();
복수형 strategies로 수정해주세요

2024-11-25 12:06 UTC, kbyunghoon commented on src/test/java/com/investmetic/domain/strategy/service/AdminStrategyServiceTest.java
> +        Strategy strategy = Strategy.builder()
이 부분은 TestEntityFactory를 사용하지 않은 이유가 있나요??

2024-11-25 16:40 UTC, 5jeong submitted a review, later dismissed

2024-11-26 10:16 UTC, 5jeong approved these changes

2024-11-26 15:54 UTC, kbyunghoon requested changes
로그 업로드는 하지 말아주세요

2024-11-27 01:16 UTC, kbyunghoon requested changes
로그파일은 지워서 올려주세요!

2024-11-27 01:16 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/strategy/controller/AdminStrategyController.java
> +@RequestMapping("/api/admin/strategies/")
`/api/admin/strategies` 로 사용해 주시고 각 매핑에 앞에 `/` 붙여서 통일해 주세용

2024-11-27 01:47 UTC, kbyunghoon approved these changes

2024-11-27 01:48 UTC, merged