Feat/question answer #47
FC-DEV-FinalProject/FinalProject_team3_BE pull request #119
Opened 2024-11-27 11:42 UTC by zjall0020

## #️⃣연관된 이슈

> ex) #이슈번호, #이슈번호

## 🔧 어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요

## ✏️ 작업 상세 내용

- [x] 문의 생성 기능 구현
- [x] 문의 삭제 기능 구현
- [x] 문의 목록 조회 기능 구현
- [x] 문의 상세 조회 기능 구현
- [x] 문의 목록 검색 기능 구현
- [x] 문의 목록 상태 기능 구현
- [x] 문의 답변 생성 기능 구현
- [x] 문의 답변 삭제 기능 구현
- [x] 문의, 답변 테스트 코드 작성

## 💡 리뷰어에게 하고 싶은 말

- 

## 🙏 아래 내용이 모두 충족 되었는지 확인해주세요 🙏

- [x] PR 이전 `dev` 브랜치 병합 하셨나요? 
- [x] PR 이전 빌드 테스트 정상적으로 성공했나요?
- [x] PR 상세내용이 충분히 기재 되었나요?
- [x] PR 리뷰어, 할당자, 라벨, 프로젝트 확인

2024-11-27 13:11 UTC, kbyunghoon requested changes

2024-11-27 13:11 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
> +        QuestionsDetailResponse response = questionService.getQuestionDetail(questionId, null, userRole);
관리자일 경우 userId는 null로 처리한 것 같은데 이 경우에는 `getQuestionDetail` 가 아닌 다른 메서드를 생성하여 호출을 다르게 받는 게 좋아보입니다.

2024-11-27 13:11 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/dto/response/QuestionsDetailResponse.java
> +                .build();
가독성이 너무 안 좋습니다...

2024-11-27 13:11 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/dto/response/QuestionsResponse.java
> +                .build();
여기도 가독성이 너무 안 좋습니다.

2024-11-27 13:11 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/model/QnaState.java
> +
이런 무의미한 커밋은 삼가해주세요

2024-11-27 15:19 UTC, kbyunghoon commented
PR 내용에 연관된 이슈와 어떤 기능인지 작성 안되어있습니다.

2024-11-28 04:04 UTC, zjall0020 commented on src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> +        return QuestionsDetailResponse.from(question, answer);
예외처리 추가했습니다!

2024-11-28 04:53 UTC, kbyunghoon requested changes
리뷰 남겼습니다.

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/controller/AnswerController.java
> +        return BaseResponse.success(SuccessCode.DELETED);
메서드를 권한 별로 나눠서 처리하고 서비스 내에서 권한 체크 해주는 게 더 좋아보입니다.

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
> +        return BaseResponse.success(response);
여기도 아래 내용 반영해주세요

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java
> +@NoArgsConstructor
확인해주세요

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/dto/request/AnswerRequestDto.java
> +    @NotBlank(message = "문의 내용을 입력해주세요.")
문의 내용이 아니라 답변 내용 아닌가요?

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/dto/response/QuestionsPageResponse.java
> +}
`PageResponseDto` 서비스 내에서 사용해주세요

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/model/entity/Question.java
>      private String strategyName; //전략명    ..?
전략 FK가 있는데 굳이 사용할 필요 없어보입니다.

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/repository/QuestionRepositoryCustomImpl.java
> +                                          String strategyName, String traderName, String investorName) {
해당 레포지토리 전부 리팩토링해주세요

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/service/AnswerService.java
> +        question.updateQnaState(QnaState.COMPLETED);
조건문에 너무 조건이 다양해서 유지보수가 힘들어보입니다.
또한 각 코드에 맞게 줄바꿈처리 해주세요

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/service/AnswerService.java
> +        }
리팩토링 해주세요..

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> +@Transactional(readOnly = true)
클래스 내에도 `Transactional` 어노테이션을 사용하고 있어서 해당 클래스 전역으로 사용할 필요도 없을 뿐더러. readOnly는 더더욱 사용하면 안될 것 같습니다.

2024-11-28 04:53 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/qna/service/QuestionService.java
> +        }
해당 조건문이 너무 자주 사용됩니다. 이 경우 메서드를 분리해서 관리자 권한 확인하는 메서드로 사용하면 좋을 것 같아요

2024-11-28 05:40 UTC, zjall0020 commented on src/main/java/com/investmetic/domain/qna/controller/QuestionController.java
> +            @RequestParam Role userRole) {
일단은 주석달아놓았습니다!

2024-11-28 06:04 UTC, zjall0020 commented on src/main/java/com/investmetic/domain/qna/repository/QuestionRepositoryCustom.java
> +}
JPQL쓰려면 나눠야된다고 커스텀이랑 임플을 따로 둬야된다고 그런던데 아닌가요? ㅠ 아니면 통합해서 하겠습니다!

2024-11-28 06:06 UTC, zjall0020 commented on src/main/java/com/investmetic/domain/qna/repository/QuestionRepositoryCustom.java
> +}
기본적인 CRUD 메서드와 커스텀 JPQL/쿼리 DSL 메서드를 분리하면 유지보수성이 향상된다고 해서 나눴습니다!

2024-11-28 06:31 UTC, zjall0020 commented on src/main/java/com/investmetic/domain/qna/model/entity/Question.java
>      private String strategyName; //전략명    ..?
삭제 했습니다!

2024-11-29 05:21 UTC, kbyunghoon requested changes

2024-12-04 04:51 UTC, merged