Feat/전화번호를 통한 이메일 찾기 기능 구현 #124
FC-DEV-FinalProject/FinalProject_team3_BE pull request #131
Opened 2024-11-29 05:39 UTC by kendrickhama

## 🔧 어떤 기능인가요?

> 전화번호를 통한 이메일 찾기 기능 구현 
>JWTFilter 버그 수정

> ## #️⃣연관된 이슈
#124 #105 

## 💡 리뷰어에게 하고 싶은 말
- 이메일,휴대번호,닉네임 중복체크 처럼 
전화번호에 해당하는 이메일이 없어도 400에러 안뜨고
result{ isFound:false}
와 같이 처리했습니다.

## 🙏 아래 내용이 모두 충족 되었는지 확인해주세요 🙏

- [ ] PR 이전 `dev` 브랜치 병합 하셨나요?
- [ ] PR 이전 빌드 테스트 정상적으로 성공했나요?
- [ ] PR 상세내용이 충분히 기재 되었나요?
- [ ] PR 리뷰어, 할당자, 라벨, 프로젝트 확인

2024-11-29 05:55 UTC, ziguin0925 reviewed
확인했습니다. 이메일 마스킹 확인하신거겠죵

2024-11-29 05:55 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/service/UserService.java
> +        // email 앞자리가 0이면
이 부분 제가 설명 적다가 만거같은데. 빼셔도 괜찮을 것 같아요.

2024-11-29 05:55 UTC, ziguin0925 commented on src/main/java/com/investmetic/global/security/filter/JWTFilter.java
나중에 loadByEmail 이라든지 getUsernaem에서 email이아니라 getEmail 했을때 email 가지고 올수 있게 수정도 부탁드릴게요.

2024-11-29 05:56 UTC, ziguin0925 submitted a review, later dismissed

2024-11-29 05:59 UTC, kendrickhama commented on src/main/java/com/investmetic/global/security/filter/JWTFilter.java
네 이 부분 security 브랜치에서 작업중입니다!
수정하겠습니다

2024-11-29 06:00 UTC, kendrickhama commented on src/main/java/com/investmetic/domain/user/service/UserService.java
> +        // email 앞자리가 0이면
네 마스킹되는거 확인했습니당

2024-11-29 09:44 UTC, ziguin0925 approved these changes
확인했습니다.

2024-11-29 15:10 UTC, kbyunghoon requested changes
리뷰 확인해주세요

2024-11-30 03:13 UTC, kendrickhama commented on src/main/java/com/investmetic/domain/user/dto/response/FoundEmailDto.java
> +}
네 null 이라고 들어가는데
안들어가는게 좋을까요?
{
  "isFound": false,
  "email": null
}
이렇게 응답됩니다

2024-11-30 11:49 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/user/dto/response/FoundEmailDto.java
> +}
네 BaseResponse 참고하셔서 null은 제외하도록 하는 어노테이션 사용해서 null은 안들어가도록 처리해주세요

2024-11-30 12:15 UTC, kendrickhama commented on src/main/java/com/investmetic/domain/user/dto/response/FoundEmailDto.java
> +}
넵 확인했습니다

2024-12-02 07:07 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/service/UserService.java
> +        }
그러면 DB에 2번 요청하게 될거같은데...

2024-12-02 07:12 UTC, ziguin0925 approved these changes
확인 했습니다.

2024-12-02 07:16 UTC, kbyunghoon approved these changes

2024-12-02 07:20 UTC, merged