Refactor/spring security 기능 리팩토링 #136
FC-DEV-FinalProject/FinalProject_team3_BE pull request #137
Opened 2024-11-29 14:05 UTC by kendrickhama

## 🔧 어떤 기능인가요?

> Security 기능 리팩토링

> ## #️⃣연관된 이슈

> #136 

## 💡 리뷰어에게 하고 싶은 말
- access_token -> access-token 로 키값 변경
- AuditConfig 추가
- username-> email로 변경

- loginSuccessHandler에서
String email = authentication.getName(); 메서드를 호출하면 
AbstractAuthenticationToken로인해 CustomUserDetails의 getUsername이 호출됩니다.
따라서 일단 getUsername을 하게되면 email을 반환하도록 하였습니다.

## 🙏 아래 내용이 모두 충족 되었는지 확인해주세요 🙏

- [x] PR 이전 `dev` 브랜치 병합 하셨나요?
- [x] PR 이전 빌드 테스트 정상적으로 성공했나요?
- [x] PR 상세내용이 충분히 기재 되었나요?
- [x] PR 리뷰어, 할당자, 라벨, 프로젝트 확인

2024-11-29 14:56 UTC, kbyunghoon requested changes
리뷰 남겼습니다.

2024-11-29 14:56 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/user/controller/UserController.java
> +        return ResponseEntity.ok("Hello, " + email);
이 메서드는 뭘까요..?

2024-11-29 14:56 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/user/dto/request/LoginRequestDto.java
> +    String password;
로그인 유지하기 없나요?

2024-11-29 14:56 UTC, kbyunghoon commented on src/main/java/com/investmetic/global/security/service/CustomUserDetailService.java
> +                .orElseThrow(() -> new UsernameNotFoundException("User not found with email: " + username));
시큐리티 예외처리로 한 이유가 있으신가용

2024-11-30 02:50 UTC, kendrickhama commented on src/main/java/com/investmetic/domain/user/controller/UserController.java
> +        return ResponseEntity.ok("Hello, " + email);
아 인증된 사용자로부터 정보 추출 테스트한거였는데 제외하고 다시 올리겠습니다

2024-11-30 08:34 UTC, ziguin0925 commented
LogoutService에서도 언더바 대신에 refresh-token, access-token으로 되어있는지 확인 부탁드립니다.

2024-11-30 15:12 UTC, ziguin0925 commented
로그인 유지에 대해서는 다시 브랜치 파서 해도 될 것 같습니다.

2024-11-30 15:16 UTC, 5jeong approved these changes

2024-11-30 15:18 UTC, ziguin0925 submitted a review, later dismissed

2024-11-30 15:32 UTC, kbyunghoon submitted a review, later dismissed

2024-11-30 15:40 UTC, 5jeong approved these changes

2024-11-30 15:44 UTC, merged