Feat/user info #10
FC-DEV-FinalProject/FinalProject_team3_BE pull request #55
Opened 2024-11-09 12:15 UTC by ziguin0925

회원 정보 쪽이라서 간단하게 작성 후 올립니다.

UserRepository, UserService, UserContorller 작성 및 테스트 코드 작성.
ErrorCode 사용자 관련 오류 코드 작성.

jwt, SecurityContext 생기면 그때 다시 리팩토링 하겠습니다.

이거 하고 s3 다시 리팩토링 하겠습니다.

close #10

2024-11-09 12:15 UTC, ziguin0925 commented
저희 ErrorCode 로 반환하는 Http상태 코드는  브라우저 상에서 모두 200 으로하는건가요?

2024-11-10 08:07 UTC, kbyunghoon commented
> 저희 ErrorCode 로 반환하는 Http상태 코드는 브라우저 상에서 모두 200 으로하는건가요?

아뇨 에러가 발생할 경우 200으로는 반환안해요. ErrorCode 확인해주세요

2024-11-10 08:16 UTC, kbyunghoon requested changes
리뷰 확인해주세요

2024-11-10 08:16 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/user/dto/response/UserProfileDto.java
> +    private String imageUrL;
카멜케이스 확인해주세요

2024-11-10 08:16 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/user/dto/request/UserModifyDto.java
> +@ToString
Data 어노테이션에는 ToString 어노테이션이 포함되어 있어 ToString은 빼도 될 것 같습니다.
근데 저는 Data 어노테이션 사용 지양하는 편이라 아래 주소 참고해보시고 수정 부탁드려요
[@Data 사용을 지양하는 이유](https://ddururiiiiiii.tistory.com/369)

2024-11-10 09:36 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/dto/request/UserModifyDto.java
> +@ToString
확인 했습니다.

2024-11-10 09:36 UTC, ziguin0925 commented on src/main/java/com/investmetic/domain/user/dto/response/UserProfileDto.java
> +    private String imageUrL;
확인했습니다.

2024-11-10 10:22 UTC, kbyunghoon approved these changes

2024-11-11 08:25 UTC, kendrickhama approved these changes

2024-11-11 08:25 UTC, merged