Feat/회원가입 기능 구현 #5
FC-DEV-FinalProject/FinalProject_team3_BE pull request #64
Opened 2024-11-14 05:56 UTC by kendrickhama

## 📌 PR 개요
- 회원가입, 이메일 전송에 대한 기능, 컨트롤러 개발

## #️⃣연관된 이슈

> 

## 📝작업 내용

-  회원가입 기능, 비밀번호 암호화 
-  이메일 전송, 인증코드 인증, 및 Redis 구현 ( 잠시 JavaMailSender로 구현했는데 추후에 스티비api 로 변경하겠습니다.)

2024-11-14 06:35 UTC, 5jeong reviewed
리뷰완료

2024-11-14 06:35 UTC, 5jeong commented on src/main/java/com/investmetic/domain/user/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<User, Long>, UserRepositoryCustom {
@Repository 는 없어도 되요!
https://velog.io/@kshired/Spring-%EC%99%9C-JPARepository%EB%8A%94-Repository%EA%B0%80-%ED%95%84%EC%9A%94-%EC%97%86%EC%9D%84%EA%B9%8C-deep-dive-%ED%95%B4%EB%B3%B4%EA%B8%B0

2024-11-14 06:35 UTC, 5jeong commented on src/main/java/com/investmetic/domain/user/controller/UserController.java
> +
지금은 응답은 필요없는것 같아여. 
+ userSignUpDto1는 요청 DTO네여 (응답은 응답 dto로)
프로필이미지 등록구현 하실때는 String으로 presignedUrL만 응답으로 보내면 될것같아요

2024-11-14 06:35 UTC, 5jeong commented on src/main/java/com/investmetic/domain/user/service/UserService.java
> +            throw new BusinessException(ErrorCode.INVALID_EMAIL);
폰검사 에러코드가 이메일이네영

2024-11-14 07:46 UTC, kbyunghoon requested changes
작성한 코드에 대한 테스트 코드가 하나도 없네요.
테스트 코드도 추가해주세요

2024-11-15 08:14 UTC, kbyunghoon approved these changes

2024-11-15 08:42 UTC, kbyunghoon approved these changes

2024-11-15 08:57 UTC, merged