Feat/구독 구독 취소 관리 기능 구현 #68
FC-DEV-FinalProject/FinalProject_team3_BE pull request #91
Opened 2024-11-21 09:44 UTC by ghkdwjdgk123

## 📌 PR 개요
- 구독 구독 취소 기능 구현 완료

## #️⃣연관된 이슈

> #68

## 📝작업 내용

- 구독 구독 취소 기능 구현 완료
-

2024-11-21 16:36 UTC, kbyunghoon requested changes
리뷰 확인해주세요.

2024-11-21 16:36 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/strategy/model/entity/Strategy.java
> +    }
메서드명이 파스칼케이스네용
스네이크 케이스로 변경해주세요

2024-11-21 16:36 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/subscription/service/SubscriptionService.java
> +    public void SubScribe(Long strategyId, Long userId) {
메서드명 스네이크케이스로 변경해주세요

2024-11-22 01:04 UTC, 5jeong reviewed
리뷰완료

2024-11-22 04:38 UTC, kbyunghoon commented on src/main/java/com/investmetic/domain/subscription/service/SubscriptionService.java
> +    public void SubScribe(Long strategyId, Long userId) {
정답

2024-11-22 04:50 UTC, 5jeong approved these changes

2024-11-22 07:17 UTC, kbyunghoon approved these changes

2024-11-22 07:21 UTC, merged